Q_net_params = {
    'layer_numbers':10,
    'conv_0':{
        'filters':256,
        'kernel_size':5,
        'strides':2,
        'padding':'SAME'
    },
    'pool_0':{
        'pool_size':3,
        'strides':2,
        'padding':'SAME'
    },
    'conv_1':{
        'filters':128,
        'kernel_size':5,
        'strides':2,
        'padding':'SAME'
    },
    'pool_1':{
        'pool_size':3,
        'strides':2,
        'padding':'SAME'
    },
    'conv_2':{
            'filters':64,
            'kernel_size':3,
            'strides':2,
            'padding':'SAME'
        },
    'pool_2':{
        'pool_size':3,
        'strides':2,
        'padding':'SAME'
    },
    'dropout_0':{
        'rate':0.5
    },
    'dense_0':{
        'shape':16
    },
    'fm_layer_0':{
        'shape':[1, 128]
    }
}

K_net_params = {
    'layer_numbers':12,
    'conv_0':{
        'filters':256,
        'kernel_size':5,
        'strides':2,
        'padding':'SAME'
    },
    'pool_0':{
        'pool_size':3,
        'strides':2,
        'padding':'SAME'
    },
    'conv_1':{
        'filters':256,
        'kernel_size':5,
        'strides':2,
        'padding':'SAME'
    },
    'pool_1':{
        'pool_size':3,
        'strides':2,
        'padding':'SAME'
    },
    'conv_2':{
        'filters':128,
        'kernel_size':5,
        'strides':2,
        'padding':'SAME'
    },
    'pool_2':{
        'pool_size':3,
        'strides':2,
        'padding':'SAME'
    },
    'conv_3':{
            'filters':64,
            'kernel_size':3,
            'strides':2,
            'padding':'SAME'
        },
    'pool_3':{
        'pool_size':3,
        'strides':2,
        'padding':'SAME'
    },
    'dropout_0':{
        'rate':0.5
    },
    'dense_0':{
        'shape':16
    },
    'fm_layer_0':{
        'shape':[1, 128]
    }
}